# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74e88eaeb223d59abbcab1ac358a7841e5c7125abd2b5542d64617aaf4ae9b96d6f985996e21b4b018b072111d7ce355da0ce5448f01f438f2c50bb44827315a

test:
  secret_key_base: 0d50fa5a93f29b2846f3eedbfd39fd17f62064aede3130dea51aa2343e8f742665b206a99ea6d64796692c45ab8b20719f6b8d254613cb302d355cbfc0467bdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
